version: "3.8"

services:
  crm-pilates-ui:
    image: crm-pilates-ui:latest
    container_name: crm-pilates-ui
    build:
      context: .
      target: production
    volumes:
      - "./src:/app/src"
    ports:
      - 3000:3000

networks:
  default:
    external: true
    name: crm-pilates_default
