version: "3.8"

services:
  crm-pilates-ui:
    image: crm-pilates-ui:latest
    container_name: crm-pilates-ui
    build:
      context: .
      target: production
    #volumes:
      #- "./volumes/app:/usr/share/nginx"
      #- "./volumes/nginx:/etc/nginx"
    ports:
      - 3000:3000
      - 80:80

networks:
  default:
    external: true
    name: crm-pilates_default
